### ISSUE TITLE
Bəzi tapşırıqlar

### ISSUE THREAD

**Issue by EldanizAkbar** [ulker1997/PragmatechFoundationProject#1]
Zəhmət olmasa aşağıdakı tapşırıqları tez bir zamanda həll et.

- [x] Lazımsız fayllları sil.(məs: layihe link.txt) Layihə linkini readme.md faylı yaradıb orda yerləşdir.
- [x] tasks qovluğundakı qovluqların adı həftəlik deyil günlük yazılmalıdı.(məs: Week02-day03)
- [x] Layihə qovluğunun adını düzgün yaz.  Layihə1 deyil Layihə olmalıdır.

**Comment by ulker1997** [comment]
done
